language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check publish bintrayUpload -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew jar -x test -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_664da3a116f7_key -iv $encrypted_664da3a116f7_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: Rvn6DvdJoioi7eRGvt2TwP/UQZg/Y43qZ1m9gmsmdLxmWxSgiAyK81uv5yWeIh7ZevRnCO0XvlJHlckmiChKz3b+xRhKeBgjpHpR8AgUU5UNMTunloQTTANKlh/77qUWO70HT4QrvoimtJ3vMBXzp6DneMX1HqRfrux/0JQwIzIKFKCfrFLsUyadAeHZXH8eFFBDIaj8PC5g4dKyofH49ByI41jGw5A1d6gnMjtGa9Cdz5jRSzrRKz4pDn6ftAjG4neQ44TWdev+V6zWyQwy5LESFe/F3x844PwBdZdMOszdpMbheqhQKhgoIabGzT4qeLpgk6AkprS7xRvFErvu9VMnJv7yomKaymUd/oGirE0LwIcXJHIihmZ75N9o/ltWeXQHb5sfhvxiyiqC90HhpwImReOt2R7TSdMo0Hsi5VM5A4cYGIdTWxT5ooNTGTtJLWkgDi3/MfOR4uBQ9JTwNEc72MnwM2/sGdb7FCk4/jN+VqJNMSEEgJs0oLauN2jBN3oARyA+ZbFUQzpFtkuT5YvUYFUdfhp3/61JWl5Hloghh/+Cos+xUQ1KNKK3lL+67UAt0KJD37cfV8f5EuIi5gxa2BvNHrVD8QRPnN8z5kZntbk+Q/xSQktV+As2A3JBl+j90fS/i5tYSrCkrB/ma8EQ17uCyMNbI5/GW4Gnfug=
  - secure: me1bdqnsCG9Yi+jBPIYN5l2oH8ZwDbfjX4aDIxmZy0a/mo8u/tV0/4fvirP+5e8Zw+Xa4XtfSiB6qugKGVpVt2sUxfvb3bjMoKsIL2TQKAqmEUegfF9tWuLjD9fP555LcfkB4fOx49vjZGjIHY93nds9oxZqNhCDL5xoD60wVaBQ6x/VYzztJHV2O7mU+5i8SnC603NjHLK0+iFHuuIY3PTX+9TU+o9uVDrBK6Ox6WFWmFW6NnuOfCc77+vOw1CiPDFa+pITPKpgvSp1WmfgSdvkfe8uk0OK+TG7HclBv+2R2EAL2MITRd8XA7xe6IcqH4kVwthSQFT8hhyVGFOC0EwYHIJ0NS2coA+EdtLEf3EfjpuhboXpOUxvRqXLLmW+2cheFKvWyl3DKZpK2OnyQBEkWTK7DBAlDGgfiU1e+49jTUS75eMAD/enkE7uuP7+DgIpUReWsi14p0AJjf7h040q78DgP04uLHIVOsRbRaCp3Hw+DpfT6Bsu/hfmkAAt2KmFta87UuYyaTYATUcr5059syL/zB/Z990HEAO8mCTwP/pkfFyXxZP6fCDfeOs3cXntvTK9R4GDmiF2tyE9sBEwXfsIkkL32moeB9hLfVfidL/zub9fHYElhMU/54duZDPVizSLF4tCrrC4EmTECV6CRBLAh/pkvM/bhK90EdY=
  - secure: xqO/Fu0J+VyC7Wb20dm4XZ/4i+Agt/Rz7JEcYBQKTn3OHkItUE75l6a2p+JFvsgyQS7JrFZIUUzJMW8yepxB+fc5B+DMtYtqFwbUicLihrfzO7kqf+gYQGTETHCftBdRozCFVgjMO29poSGQkN67niWhowjz/jWmbU6h3FGZiWBLdsYtK2Y5mk+bOoje7dXeMPw0yaOWS7dBy/Wrwz5tQguptawlqmSzYpWRK/xPmMNFzZjcDge4bzF4huLGMt8WJxIbr8oXpAZqWOvV5sr46E5puw+xsDG7kZohSrqEBjhLKI6bT3rXOh1tKx0ebnEqeXS/sbzC+ieTsRypBkot7uqMgSHBzf5GYfbBeI9xJPA6PVq6FxP46PxZ7KV1VXRZKxwJ0luoH1HN2hXWiwXbEdNR7xWKvp9xBk5j/AW6+q3rd9ESBF2xftq0rSm1roRamPIOznvKr1/wjyv6L0HfqXUUUOO7P0xPWNYgSCE3LITMdV1HSRcFXPUnE+bGXuIo5ux0m3FhjC8F6kCDe+mBeAdgBMd7LJNrrHvH25Pgk7XUb1s1zryjudxGKI/5+ffFhRoyW/EG7fB2nkYgSjwrjeq45QzFebOU+Ip1oJzeQj+aWxnQCdsV5LRZbsLTmSjdUPwVaj3HTqRda0Ueg+0lxj7EJf64ausm0eOSI9dkLH4=
  - secure: FnhhKCaNJobPl2PAD1aq+gC7z5MalUoigYjiZRUlf1DVXraEuzXiCJfskL7m2U49zydRfTG9GWEZvC2NPWy3AMSGpY9rDT0IGW+WWk0U8kl8ES3J64Z5Ms2IeOrLxSrowfPJncFbmb6Lp+nqIdDEgRek7/c8Z4x/evBTSiunPl9reOnZh8dsaRccecSwylso6rwraTAsoSodGB92yKFMYE5uBlejiV6s7Q3eP+kNO9tpZ4e8NtsCiVn1Hq5s5K2CNr3qF0oIs6TCPVMoR7iwWha6+2inC9+mlrc0NoHDLUP6SqI79kLunV0wNh4t6ov5YpWaN8tUGMvK9kOWQZdSJALMLgzmh7HxxR5iogV1ohWJnW61hE4uaPYtQb4Vc+3lT6sB3fESY0yxDVC54OfQKQnymwpaoq6MNin5+9kMNfBoMyc/GUuh1TcC7V+zGldsfZ1PpqD+LY486IkTtyZkVCrSApq7s1ivuC1MzVLYtV6PKErypwYtLUNycXCJhGL/ksSot/1v+8xdfwyDJ4/CJEqyPXxXTSQmUh5u3b1UvyhzznT9I2KpG4Liybxc3axOFaXPpZVyuO9PoYEY1tT4xTmf3nab6AKBTsLfmpaaTuiZLsMjyXOpt+dO5ZMgKvACmBLigsmhWz9vzeXvbL3jjofHwqwhMthmvLemA/Pud9M=
  - secure: hSP5T3OPQBVEhJH0IjMf+oo+XQV0YkFbwOhEPoYPb87sqwwsXkXCNJq2aI0YBM2S+tfDqUwaFRS7/+thirsI22YQwX1JIvKMrAZuBneqE6KG4wMPJjDsUHr0M3/mrFkX4Jta2MuFvh2LX4FJ0IZll8Jy2MlfLu+CvxmWmHbALprBcWxeHquqBsiYI6BntFRAG4S7REh0S36GZygOvxNd5dJkifq4FsVM7AHbX0uargecNbilpZ77AzxdMuKuF/53a3ZxBe5kpHUArcHmt/qMRYeaiCPdbltctLnf4oeOKYsBew7KHcz7DHSQTV7zubXBM6ZB3kn5ebQOn8AdSSoCkgHZITkLWDaGQSoxxEyNPxeYyDg4W/smBNOQ1Uq/aODhIpQ8Jbt5SSwk9PavfoK/8aEdUEye2lgNpwMSdeGCDlBDWUN8T4ZckevMBECwFTpXs1m43KMHFODBE0gKYwQuYW6RIz0pIKxui8SvjZBKu554/xLXOIurl5DxqW5OlvQV1qOqu0ACbLHV2j0xEIMpX1RSHzyWNyTOEX8hIrGJAwEBU1o0nUsk/ph5ow9eePWHHwgxzdHSqFOS8XElfiJCmNXWt5rX8QYEojyXdzkUbxuEGPFzuyWC++8xZkz5CFyrgnrfLbjBf16imTNtbRJlhbJVzkhlI3wMPO3vuFnW6/w=
  - secure: Ixf10lpxbl3vH+tM2JKf88la7q90hC8yh7DK8urS0nisTAsX6oSL91LeWiS8IQWtB3wlDwfV6JxWfOY0jpifeB5rChrrubDf95aRu4k1/LzByaVwxjkWsP8J67YNZVp71ivr5Wq7I7TAVRVv/r7WE83ApYwKb7evjb9ml+MUZo6GzpE/Ki2bNy5rr6XeQW6AiAg1VoWqFGss5doPjxE35A2K/2pZKihtthxZ9VffaaJgnA3Tm04jpl4cSbivw6aqQKWzobzRJ1rfaO7HzWysgCjuDvO/5Fjk/ms/eNr55X8C6U6kiFaT0Gn7r/UW+xCT1wFFl75c74OFGPcNHSQADkwWtk8cvMycl3JUJwROyJIuFY+r+Dr/NTk1q25CDh4t9nqK1269CMWVNyOLrnmXFOA2+2s3qWhQykcyEY8EZl2p9Wu8XznxSfmu3HLpF+zIiZ1rEn6U0gYEHneJsQipxdT0La281mXI3jucDd33qnnjIeqhPipehHokMLUG38fLDU6/l8XGT4tnM12vxUDE/rtcjxk03P91zmFG3MtqXUyhfMOcmXvngaedqFcKkGm1sLG8dJ655PT30iAGmBgkRsVQFtfaaIFBwA4HmKEqlx8BBONBu+Qxel3AHH4xe99rKpt0+vwCrZZ6u2r30xyMvqq7CUK7UgYswmkJcU15KOI=
